### ISSUE TITLE
In viewer in notebooks, if you change camera, the view gets blank

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-viewer#166]
The view also gets blank the first time you load the model until you click play.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab This should be solved in dev right now. I just tested on one of the notebooks with a model containing three cameras that was failing before and it works now. Can you confirm if it works for you?

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz I tested it using an old gltf file with multiple cameras and it seemed to work properly. However for the workshop I'll continue to not embed cameras in gltf files since it's not emphasized in the demo anyway and we have only limited testing cycles to put on it. Thanks for the fix 👍
