### ISSUE TITLE
Bottom Drawer fails to show by default on a phone screen

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#34]
Need to scroll the window up to see the buttons

**Comment by AlbertoCasasOrtiz** [comment]
Looks like this is a problem of mobile navigators, since the height of the viewport is not considering the search bar and additional bars created by the navigator in top of the content.

For example, in brave you have search bar at top, and options bar at bottom of I scroll down and then I scroll up, those bars disappear and everything is visible.

![Screenshot_20230417-211125-01.jpeg](https://user-images.githubusercontent.com/15672785/232669840-7eb90dc8-6c7b-49bf-8dd5-2b99e2e960d4.jpeg)

![Screenshot_20230417-211134-01.jpeg](https://user-images.githubusercontent.com/15672785/232669858-e8be29e2-07cd-4f18-b2cf-0080224449bb.jpeg)
