### ISSUE TITLE
Add texture coordinates/texture to one bone file (skull) and document the steps

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#42]
Now that we have the models for the visualizer baked into the repository we can improve the aesthetics by adding texture to the bones. Likely this will involve taking the bone into blender or another tool to unwrap it (at less prominent seams) and apply a texture to it to test. E.g. https://tileable.co/discover/bone/

**Comment by aymanhab** [comment]
The experience of @fcanderson and/or @tkuchida would be very helpful here

**Comment by tkuchida** [comment]
I tried a few strategies for the images in the textbook, including texture mapping the way you're "supposed" to do it, generating the textures procedurally, and a giant hack. The giant hack worked best and looked good enough (but don't tell my old graphics prof I did it this way 😉 ). Briefly, I used a generic bone-like texture tile and mapped it onto each triangle independently, calculating texture coordinates for each triangle from across the entire texture tile. This won't work in general since you're just naively stamping the texture tile onto each triangle, but it worked in this case because the texture itself hides the seams between triangles. (As long as there aren't any large features on the texture tile, you won't notice if a feature is partially cut off at an edge.) This strategy only required one relatively small texture tile and could be applied to any bone mesh without calculating/storing texture coordinates specifically for each mesh. Happy to discuss the details if that would be helpful. 🦴

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz If you can document the steps in Blender for one file that would be great. Thank you

**Comment by AlbertoCasasOrtiz** [comment]
I have created a Blender script for this.

Inputs:

- `texture_path`: Path to the texture file.
- `folder_path`: Input folder path with vtp files.
- `output_folder`: Output folder path where the generated obj and mtl files are stored.
- `apply_sub_surface`: True to apply subdivision surface modifier with 1 subdivisions.
- `specular`: Specular component of the material.
- `roughness`: Roughness component of the material.

For every vtp file in the input folder, the script does the following:
1. **Import** vtp file into Blender.
2. Create a **material** with specified roughness and specular components.
3. Create an **UV map** using Smart UV Unwrap.
4. Add the **texture** file to the material.
5. Add and apply a **Subdivision Surface Modifier** to make the mesh look smoother (Optional).

The script is stored [here](https://gist.github.com/AlbertoCasasOrtiz/92db190ee950786e5aefcb876fe5d3c8).

This is how the result looks (with subdivision surface):

![Screenshot 2024-10-22 153322](https://github.com/user-attachments/assets/28e17623-b4df-4e29-9d31-0c719afc1242)

This is the texture file I am using (CC0 License):
![concrete](https://github.com/user-attachments/assets/093a8026-065f-404f-89a0-21b8814b5541)

**Comment by AlbertoCasasOrtiz** [comment]
I am using CC0 licensed textures from [OpenGameArt](https://opengameart.org/)

Specifically [this one](https://opengameart.org/node/10162) from [this package ](https://opengameart.org/content/seamless-textures).

**Comment by tkuchida** [comment]
@aymanhab 

Texture:
![](https://github.com/user-attachments/assets/7cb20775-3517-4d0e-97cd-37a16434ec64)

Bump map:
![](https://github.com/user-attachments/assets/40a881e5-470b-4257-b205-0e5352ed53b3)

Example:
![](https://github.com/user-attachments/assets/2cb7ee97-a9aa-469f-814e-4e42d2f2388a)
