### ISSUE TITLE
Encapsulate a visualizer in a Web application / HTML page

### ISSUE THREAD

**Issue by jsn-inrs** [opensim-org/opensim-viewer#95]
As explained in the topic [How to include a visualisation in a web (html) page ?](https://simtk.org/plugins/phpBB/viewtopic.php?f=91&t=16929&sid=d8b51b4b65be44166ec97e2ca6a7234e) in OpenSim's forum, I'd like to insert the Visualizer in a HTML canvas (or something like that), so that the 3D-model can be displayed in a web application in a common browser (Firefox, Chrome). Is it possible at the moment ? The idea is to run features based on OpenSim's API from a web application, without having to install the entire software and its graphical interface on a dedicated workstation. Please do not hesitate to contact me for any further information.

**Comment by aymanhab** [comment]
Thanks for the note, this is what we're actively working on in this repo. If you follow the link here you'll see where it stands for some baked in models, we're making this more general and available for the community and to handle arbitrary models. 
https://comforting-speculoos-d9e100.netlify.app/models

In the meantime if you need specific functionality in the 3D view please describe here or on separate issues. Thank you

**Comment by jsn-inrs** [comment]
Very fine, thank you, Arm26 should be a first use case. MoBL model (upper arm from the paper of Saul et al.) would be ideal, if possible.

**Comment by jsn-inrs** [comment]
Actually, I think I don't need another feature in the 3D view. What I plan is to have a web page which includes:

- sliders and/or edit box to set the value of each joint angle of all DoFs of the model
- a check box to select up to 3 DoFs of the model
- the associated posture of the model displayed in the viewer in a canvas
- another canvas with a 2D or 3D plot built by a script run from the previous values / choices.

If someone has already built something similar, or if someone could help do so, I'm very interested in.

**Comment by aymanhab** [comment]
Thanks for the details/feedback, one key detail to point out here is that the name "viewer" was intentional to indicate visualization/plotting of precomputed motions/results rather than create fresh/new ones. 

For example, posing a model through a trajectory can be precomputed and rendered without a problem (with OpenSim running on the backend, computing muscle wrapping and satisfying constraints etc.), however arbitrary combinations of sliders that produce novel poses as done by the GUI would require either running the OpenSim API/engine in the browser or expensive communication with the backend. So the plan is to allow for the specification of a json file that describes what sliders the user wants and also a chart/group-of-charts describing what quantities to plot (at least as of now).

Would love to hear your thoughts and the use case you have in mind so we can brainstorm and/or come up with a satisfactory solution.

**Comment by jsn-inrs** [comment]
Thank you for your answer and your interest in my request. Can we continue this discussion via private messages so that I can send you information about work that has not yet been published?

**Comment by aymanhab** [comment]
Sure, let's pick up the discussion by email.

Best regards,
-Ayman

**Comment by aymanhab** [comment]
Will close as the general issue is being addressed, specific discussion don't belong here
